name_city = (input("please enter your full name and what city you are from: "))
print(len(name_city))
print(name_city.upper())
print(name_city.lower())
print(name_city.startswith("Toni"))
print(name_city.endswith("Azor"))
print(name_city.split())
print(name_city.replace(" ", "*"))
print(name_city.split("*"))
print(name_city.center(50, "="))
print(name_city[3:])
print(name_city[:4])
print(name_city[1::2])
print(name_city.title())